on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    # at 1PM on Sundays
    - cron: '00 13 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: 'https://community.r-multiverse.org https://etiennebacher.r-universe.dev'

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render Rmarkdown files
        run: |
          rmarkdown::render("dashboard.Rmd", output_dir = "public")
        shell: Rscript {0}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.TIDYPOLARS_DASHBOARD_PAT }}
          publish_dir: ./public
          force_orphan: true
